"""
License Tracker v2.0
Tracks image/video asset licenses and maintains a database of approved sources.
Prevents DMCA strikes and Content ID claims.
"""
import os, json
from datetime import datetime


class LicenseTracker:
    """
    Tracks visual asset licenses and maintains safe source database.
    Runs pre-pipeline to ensure all images used in production are properly licensed.
    """

    # Pre-approved image sources with their license types
    APPROVED_SOURCES = {
        "unsplash": {
            "license": "Unsplash License (free for commercial use, no attribution required)",
            "commercial_safe": True,
            "attribution_required": False,
            "notes": "Safe for all content. Download API available.",
        },
        "pexels": {
            "license": "Pexels License (free for commercial use, no attribution required)",
            "commercial_safe": True,
            "attribution_required": False,
            "notes": "Safe for all content. Good for news imagery.",
        },
        "pixabay": {
            "license": "Pixabay License (free for commercial use, no attribution required)",
            "commercial_safe": True,
            "attribution_required": False,
            "notes": "Safe for all content. Large library.",
        },
        "wikimedia_commons": {
            "license": "Varies by image — check individual Creative Commons license",
            "commercial_safe": True,
            "attribution_required": True,
            "notes": "Usually CC-BY or CC-BY-SA. Verify per-image. Avoid CC-NC for monetized content.",
        },
        "original_screenshots": {
            "license": "Original Fair Use (news reporting, commentary, education)",
            "commercial_safe": True,
            "attribution_required": True,
            "notes": "News screenshots fall under fair use for commentary. Keep minimal.",
        },
        "generated_ai": {
            "license": "AI-generated (no copyright, but YouTube requires disclosure)",
            "commercial_safe": True,
            "attribution_required": False,
            "notes": "AI images are not copyrightable. Must disclose AI use in description.",
        },
        "local_slideshow": {
            "license": "Original (generated by ViralDNA pipeline)",
            "commercial_safe": True,
            "attribution_required": False,
            "notes": "Safe — all images self-generated from licensed sources.",
        },
    }

    # Sources to avoid
    BLOCKED_SOURCES = [
        "getty_images",
        "shutterstock",
        "alamy",
        "afp",
        "reuters_images",
        "ap_images",
        "istock",
        "adobe_stock",
        "dreamstime",
        "123rf",
    ]

    def __init__(self, *args, **kwargs):
        self.db_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "diagnostics", "license_db.json"
        )
        self._load_db()

    # ── Track Asset ─────────────────────────────────────────────────────

    def track_asset(self, asset_path: str, source: str, license_type: str,
                    commercial_safe: bool = True, attribution_required: bool = False,
                    notes: str = ""):
        """Register an asset in the license database."""
        asset_record = {
            "path": asset_path,
            "source": source,
            "license": license_type,
            "commercial_safe": commercial_safe,
            "attribution_required": attribution_required,
            "notes": notes,
            "tracked_at": datetime.now().isoformat(),
        }
        self.db["assets"].append(asset_record)
        self.db["stats"]["total_tracked"] = len(self.db["assets"])
        self.db["stats"]["commercial_safe"] = sum(
            1 for a in self.db["assets"] if a.get("commercial_safe")
        )
        self._save_db()

    # ── Stats ───────────────────────────────────────────────────────────

    def get_stats(self) -> dict:
        """
        Returns license tracking statistics.
        Called by LicenseComplianceAgent pre-pipeline.
        """
        if not self.db.get("assets"):
            return {
                "total_tracked": 0,
                "commercial_safe": 0,
                "attribution_required": 0,
                "violation_count": 0,
                "blocked_source_count": 0,
                "status": "empty",
                "message": "No assets tracked yet. License DB is clean.",
            }

        assets = self.db["assets"]
        attribution_count = sum(1 for a in assets if a.get("attribution_required"))
        violation_count = sum(1 for a in assets if a.get("license_violation"))
        blocked_count = sum(1 for a in assets if a.get("source") in self.BLOCKED_SOURCES)

        return {
            "total_tracked": len(assets),
            "commercial_safe": sum(1 for a in assets if a.get("commercial_safe")),
            "attribution_required": attribution_count,
            "violation_count": violation_count,
            "blocked_source_count": blocked_count,
            "status": "ok",
            "last_tracked": assets[-1].get("tracked_at", "unknown") if assets else None,
        }

    # ── Safe Sources ────────────────────────────────────────────────────

    def get_safe_sources(self) -> list:
        """
        Returns list of approved image sources for the current pipeline run.
        Called by LicenseComplianceAgent pre-pipeline.
        """
        return sorted(self.APPROVED_SOURCES.keys())

    # ── Source Verification ──────────────────────────────────────────────

    def verify_source(self, source: str) -> dict:
        """
        Verify if an image source is safe to use.
        """
        source_lower = source.lower().strip()

        if source_lower in self.APPROVED_SOURCES:
            info = self.APPROVED_SOURCES[source_lower]
            return {
                "source": source,
                "approved": True,
                "commercial_safe": info["commercial_safe"],
                "attribution_required": info["attribution_required"],
                "license": info["license"],
                "notes": info["notes"],
            }

        if source_lower in self.BLOCKED_SOURCES:
            return {
                "source": source,
                "approved": False,
                "commercial_safe": False,
                "blocked": True,
                "warning": f"'{source}' is a PAID stock service. Using without a license WILL cause DMCA/Content ID.",
                "recommendation": "Switch to Unsplash, Pexels, Pixabay, or local slideshow images.",
            }

        return {
            "source": source,
            "approved": False,
            "unknown": True,
            "warning": f"'{source}' is not in the approved or blocked database.",
            "recommendation": "Verify license manually before use. Prefer known safe sources.",
        }

    # ── Violation Recording ─────────────────────────────────────────────

    def record_violation(self, asset_path: str, reason: str):
        """Record a license violation for tracking."""
        self.db["violations"].append({
            "asset_path": asset_path,
            "reason": reason,
            "recorded_at": datetime.now().isoformat(),
        })
        self.db["stats"]["violation_count"] = len(self.db["violations"])
        self._save_db()

    # ── Internal ────────────────────────────────────────────────────────

    def _load_db(self):
        try:
            if os.path.exists(self.db_path):
                with open(self.db_path, "r") as f:
                    self.db = json.load(f)
            else:
                self.db = {"assets": [], "violations": [], "stats": {"total_tracked": 0, "violation_count": 0}}
        except Exception:
            self.db = {"assets": [], "violations": [], "stats": {"total_tracked": 0, "violation_count": 0}}

    def _save_db(self):
        try:
            os.makedirs(os.path.dirname(self.db_path), exist_ok=True)
            with open(self.db_path, "w") as f:
                json.dump(self.db, f, indent=2, default=str)
        except Exception:
            pass

    # ── Legacy pass-through ─────────────────────────────────────────────

    def execute(self, state):
        return state
